itwm_example/example_plugin.py
itwm_example/fixed_value_data_source/fixed_value_data_source.py
itwm_example/fixed_value_data_source/fixed_value_data_source_factory.py
itwm_example/fixed_value_data_source/fixed_value_data_source_model.py

A simple data source that returns a fixed value, specified in the model

Added fixed value data source

---

itwm_example/example_plugin.py
itwm_example/production_cost_data_source/production_cost_data_source.py
itwm_example/production_cost_data_source/production_cost_data_source_factory.py
itwm_example/production_cost_data_source/production_cost_data_source_model.py

Adds a data source for computing the production cost (heat cost)

Introduced heat production cost

---

itwm_example/material_cost_data_source/material_cost_data_source.py
itwm_example/material_cost_data_source/material_cost_data_source_factory.py
itwm_example/material_cost_data_source/material_cost_data_source_model.py

Adds a plugin for computing the material cost

Basic implementation of material cost evaluation

---

force_bdss_prototype/__main__.py

Adds a main program so that we can start the evaluation of the prototype

Added main program

---

force_bdss_prototype/MCOwrapper.py
force_bdss_prototype/__main__.py
force_bdss_prototype/constraints.py
force_bdss_prototype/initializer.py
force_bdss_prototype/material_db_access.py
force_bdss_prototype/objectives.py
force_bdss_prototype/pareto_process_db.py
force_bdss_prototype/process_db_access.py
force_bdss_prototype/reaction_kinetics.py
force_bdss_prototype/reaction_knowledge_access.py
force_bdss_prototype/tests/test_constraints.py
force_bdss_prototype/tests/test_material_db_access.py
force_bdss_prototype/tests/test_reaction_kinetics.py
force_bdss_prototype/tests/test_reaction_knowledge_access.py

Removed code that is not used or is irrelevant for an initial prototype.

Prototype cleanup

---

itwm_example/example_plugin.py
itwm_example/pure_densities/pure_densities.py
itwm_example/pure_densities/pure_densities_factory.py
itwm_example/pure_densities/pure_densities_model.py

Adds a data source for the pure densities of the various reactants A, B, and impurity C.

Pure densities model provides the densities of the various reactants

---

itwm_example/arrhenius_parameters/arrhenius_parameters.py
itwm_example/arrhenius_parameters/arrhenius_parameters_factory.py
itwm_example/arrhenius_parameters/arrhenius_parameters_model.py
itwm_example/example_plugin.py

Provides a data source delivering the arrhenius parameters (nu and delta H) for the main and secondary reactions. These values will be delivered to the impurity evaluator in the evaluation network.

Added arrhenius parameters

---

itwm_example/impurity_concentration/impurity_concentration_data_source.py

Fixed the Reaction kinetics for the new parameters provided by ArrheniusParameters and PureDensities

Impurities concentration change for new parameters 

---

itwm_example/material_cost_data_source/material_cost_data_source.py

Fixes the incorrect slots for the material cost data source. The input slot should not be cost.

Fixes incorrect slots for the material cost data source

---

itwm_example/impurity_concentration/impurity_concentration_data_source.py

The impurity concentration was not returning the appropriate data type.

Fixes incorrect return type for impurity concentration.

---

itwm_example/csv_writer/csv_writer.py

The CSV writer was missing the model from its declaration.

Added missing model to the CSV Writer

---

itwm_example/csv_writer/csv_writer.py

Added formatting of the values, and truncation of the file at initialization

Minor improvement to csv class.

---

itwm_example/example_plugin.py

Adds name and description to plugin for representation in the plugin manager

Adds name and description to plugin

---

itwm_example/mco/mco.py
itwm_example/mco/mco_model.py

Implements the direct mode of execution of the MCO, without spawning an external process.

Implementation of direct execution

---

.travis.yml
ci/__main__.py

Matches current master on force-bdss.

Ports the travis build to python 3 exclusively

---

itwm_example/csv_writer/csv_writer.py
itwm_example/mco/mco.py

Sync against changes in force-bdss PR 187.

Update MCO for new design of MCOProgressEvent

---

itwm_example/mco/mco_factory.py

Changes the MCOFactory to return classes instead of instances for the MCO parameters

Updated against BDSS PR 191

---

itwm_example/mco/mco.py

Inclusion of scaling factors affect weights in weighted cost function.
Pre-requisite pull request = https://github.com/force-h2020/force-bdss/pull/215 https://github.com/force-h2020/force-wfmanager/pull/272

Inclusion of scale_factor for KPIs

---

ci/__main__.py

See https://github.com/force-h2020/force-bdss-plugin-enthought-example/pull/25

Updated scipy to 1.2.1

---

.travis.yml

(left in previous PR by mistake)

FIX: Change BDSS branch in travis-ci.yml
